# fly.toml app configuration file generated for titanic-ml-api-kjh on 2023-08-08T11:21:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "titanic-ml-api-kjh"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"
  
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]
